### ISSUE TITLE
Can't find "Charts" module

### ISSUE THREAD

**Issue by JJBarata** [UPetersen/LibreMonitor#11]
Hi! I downloaded the latest files and followed all their guidelines, however, when trying to build the application, I'm getting some warnings and a strange error that refers to importing the module "Charts", which it does not find. Here are the screenshots. What am I doing wrong? Tks.

![erro1](https://user-images.githubusercontent.com/12895638/39247329-7444e0d8-486f-11e8-99cc-ea6f08e91aa1.png)

![erro2](https://user-images.githubusercontent.com/12895638/39247337-7c8c2148-486f-11e8-82b7-a46321e3feff.png)

![erro3](https://user-images.githubusercontent.com/12895638/39247344-81974f96-486f-11e8-950a-f1c31b3a94e4.png)

**Comment by UPetersen** [comment]
Which branch did you use? 
I just downloaded the swift 4 branch and opened it with Xcode 9.3 and it worked (tested with the iPhone 8 plus simulator. To really run it with bluetooth you need a real phone). You have to run "pod install" (requires [cocoapods](https://cocoapods.org)) in the project directory from the command line in order to install the [charts](https://github.com/danielgindi/Charts) library. If you do not want to use cocoapods, there are other ways to install the charts library, see [here](https://github.com/danielgindi/Charts).

What hardware will you be using? 
If you have a miaomaio, use the most recent version of the swift 4 branch. If you use simblee or rfduino as hardware, use the commit from 25 Nov. 2017, i.e. before the changes for miaomiao where made. 

Hope this helps.

**Comment by JJBarata** [comment]
Thanks for reply!

I used master branch on swift 4 and xcode 9.3 environment. I did all steps that you suggested (installed cocoapods, ran "pod install" on project folder, opened "LibreMonitor.xcworkspace", cleaned build folder, added "Charts.framework" on Embedded Binaries and tested on iPhone SE) but when I test, appear all issues on Charts. I did it right?

I using Simblee hardware with BM019 module.

I will test with 25 Nov. 2017 branch and I will post here the results.

Thank you very much and congratulations for your awesome project!!

**Comment by JJBarata** [comment]
Well, I ran now and return one error, at least! I noticed that all errors occur because of the Charts. I made some changes on Pods and Charts build settings like prints bellow.

![erro4](https://user-images.githubusercontent.com/12895638/39303194-9cb9e9ca-492b-11e8-9602-f02492af6b16.png)

![erro5](https://user-images.githubusercontent.com/12895638/39303201-a225e738-492b-11e8-8572-81ea5b1ff9cf.png)

![erro6](https://user-images.githubusercontent.com/12895638/39303208-a7cabf60-492b-11e8-88d9-03928f050708.png)

Out of curiosity, when I install the Chart, it returns the informations bellow.

![erro7](https://user-images.githubusercontent.com/12895638/39303393-50ddce6c-492c-11e8-9885-9201ee9579f7.png)

Thanks!!

**Comment by JJBarata** [comment]
I made it work. I ran on my iPhone 7 Plus. I installed Charts with Carthage, as you indicated. Now I will configure the Simblee and the BM019 to be able to scan the FL.

![libremonitor](https://user-images.githubusercontent.com/12895638/39307724-f8cf6970-4939-11e8-9aad-9bbf7731c76f.png)

Thank you very much!!

**Comment by UPetersen** [comment]
😄
